# Generated by Django 5.2.7 on 2025-10-31 02:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('hex_code', models.CharField(default='#000000', help_text='Formato: #RRGGBB (ejemplo: #FF0000 para rojo)', max_length=7, verbose_name='Código Hexadecimal')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['order', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='marcas/', verbose_name='Logo')),
                ('website', models.URLField(blank=True, verbose_name='Sitio web')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Talle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True, verbose_name='Talle')),
                ('abbreviation', models.CharField(help_text='Ej: XS, S, M, L, XL', max_length=10, verbose_name='Abreviatura')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Talle',
                'verbose_name_plural': 'Talles',
                'ordering': ['order', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen principal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='productos.categoria', verbose_name='Categoría')),
                ('colores', models.ManyToManyField(blank=True, related_name='colores', to='productos.color', verbose_name='Colores disponibles')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcas', to='productos.marca', verbose_name='Marca')),
                ('talle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='talles', to='productos.talle', verbose_name='Talle')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.color', verbose_name='Color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='productos.producto', verbose_name='Producto')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.talle', verbose_name='Talle')),
            ],
            options={
                'verbose_name': 'Stock de producto',
                'verbose_name_plural': 'Stock de productos',
                'ordering': ['product', 'color__order', 'talle__order'],
                'unique_together': {('product', 'color', 'talle')},
            },
        ),
    ]
