# Generated by Django 5.2.7 on 2025-10-31 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productostock',
            options={'ordering': ['producto', 'color__order', 'talle__order'], 'verbose_name': 'Stock de producto', 'verbose_name_plural': 'Stock de productos'},
        ),
        migrations.RenameField(
            model_name='productostock',
            old_name='product',
            new_name='producto',
        ),
        migrations.AlterField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(blank=True, related_name='productos', to='productos.color', verbose_name='Colores disponibles'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.talle', verbose_name='Talle'),
        ),
        migrations.AlterUniqueTogether(
            name='productostock',
            unique_together={('producto', 'color', 'talle')},
        ),
    ]
