# Generated by Django 5.2.7 on 2025-11-06 03:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_cliente_grupocliente_direccion_cliente_grupo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='ID de Sesión')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'ordering': ['-actualizado'],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('agregado', models.DateTimeField(auto_now_add=True, verbose_name='Agregado')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.carrito', verbose_name='Carrito')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.color', verbose_name='Color')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto')),
                ('talle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.talle', verbose_name='Talle')),
            ],
            options={
                'verbose_name': 'Item del Carrito',
                'verbose_name_plural': 'Items del Carrito',
                'unique_together': {('carrito', 'producto', 'color', 'talle')},
            },
        ),
    ]
