# Generated by Django 5.2.7 on 2025-11-06 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_carrito_carritoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productostock',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productostock', to='productos.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='talle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productostock', to='productos.talle', verbose_name='Talle'),
        ),
    ]
