# Generated by Django 5.2.7 on 2025-11-07 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_productostock_color_alter_productostock_talle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='productos.carrito', verbose_name='Carrito'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='talle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.talle', verbose_name='Talle'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='productos.grupocliente', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='productos.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categorias', to='productos.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='colores',
            field=models.ManyToManyField(blank=True, related_name='productos', to='productos.color', verbose_name='Colores disponibles'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='talle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.talle', verbose_name='Talle'),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productostock', to='productos.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='productos.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productostock',
            name='talle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productostock', to='productos.talle', verbose_name='Talle'),
        ),
    ]
