# Generated by Django 5.2.8 on 2026-04-27 01:18

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_alter_carritoitem_carrito_alter_carritoitem_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='Está activo'),
        ),
        migrations.AddField(
            model_name='talle',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='Está activo'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='País'),
        ),
    ]
