# Generated by Django 5.2.8 on 2026-04-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_color_esta_activo_talle_esta_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ultima_visita',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Visit'),
        ),
    ]
