# Generated by Django 5.2.8 on 2026-04-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_alter_cliente_ultima_visita'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='esta_activo',
            field=models.BooleanField(default=True, verbose_name='Está activo'),
        ),
    ]
