# Generated by Django 5.2.8 on 2026-05-01 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_cupon_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='productos.categoria', verbose_name='Categoría Padre'),
        ),
    ]
