# Generated by Django 4.2.25 on 2025-11-01 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productostock_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamiento', models.CharField(choices=[('SR', 'Sr.'), ('SRA', 'Sra.'), ('SRTA', 'Srta.'), ('DR', 'Dr.'), ('DRA', 'Dra.')], default='SR', max_length=10, verbose_name='Tratamiento')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('ventas_totales', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ventas Totales')),
                ('activado', models.BooleanField(default=True, verbose_name='Cuenta Activada')),
                ('boletin', models.BooleanField(default=False, verbose_name='Suscrito a Boletín')),
                ('ofertas_asociados', models.BooleanField(default=False, verbose_name='Ofertas de Asociados')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('ultima_visita', models.DateTimeField(blank=True, null=True, verbose_name='Última Visita')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='GrupoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Grupo')),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento para este grupo', max_digits=5, verbose_name='Descuento (%)')),
            ],
            options={
                'verbose_name': 'Grupo de Cliente',
                'verbose_name_plural': 'Grupos de Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('codigo_postal', models.CharField(max_length=20, verbose_name='Código Postal/Zip')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('es_predeterminada', models.BooleanField(default=False, verbose_name='Dirección Predeterminada')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='products.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'ordering': ['-es_predeterminada', 'cliente'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='products.grupocliente', verbose_name='Grupo'),
        ),
    ]
